### ISSUE TITLE
✨ Feature request: New check endpoint / agents module

### ISSUE THREAD

**Issue by nwerker** [svalabs/sva.sentinelone#13]
Suggest an idea for this project

##### SUMMARY
There should be a new module which checks a number of agents / endpoints against the S1 API. It should check is the endpoint registred, has a desired status (active true or false), is correctly in a given set of sites and maybe if the agent is unique. Through additional fields the API Call can be customized by the user.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
sentinelone_check_endpoint.py
sva.sentinelone.sentinelone_check_endpoint

##### ADDITIONAL INFORMATION

This could be a list of input parameters:
```python
    module_args = dict(
        console_url=dict(type='str', required=True),
        token=dict(type='str', required=True, no_log=True),
        endpoints=dict(type='list', required=True, elements='str'),
        sites=dict(type='list', required=False, elements='str'),
        active=dict(type='bool', required=False),
        unique=dict(type='bool', required=False),
        additional_fields=dict(type='dict', required=False, elements='str')
    )
```

```yaml
- name: "Check if agent is registred correctly
  sva.sentinelone.sentinelone_check_endpoint:
    console_url="https://XYZ.sentinelone.net"
    token="XXXXXXXXXXXXXX"
    endpoints:
      - "my_computer01"
    active: true

- name: "Check if list of endpoints is registered correctly
  sva.sentinelone.sentinelone_check_endpoint:
    console_url="https://XYZ.sentinelone.net"
    token="XXXXXXXXXXXXXX"
    endpoints:
       - "my_computer01"
       - "tims_desktop01"
       - "farm_server04"
    sites:
       - "my_site01"   
```

Return Values should be the return by the API and the state of the module should be dictated by the input parameters. e.g: Fail if the endpoint is registered but in more or less sites than expected. Or fail if the endpoints don't match the active state. This can be used to check if the agent is registered correctly. For instance after an automatic installation
