### ISSUE TITLE
📖 Documentation Report: Wrong example in sentinelone_filters module

### ISSUE THREAD

**Issue by nwerker** [svalabs/sva.sentinelone#15]
##### SUMMARY
Following Documentation is missleading:
https://svalabs.github.io/sva.sentinelone/branch/main/collections/sva/sentinelone/sentinelone_filters_module.html#ansible-collections-sva-sentinelone-sentinelone-filters-module

In the first example it says:

```yaml
---
- name: Create filter
  sentinelone_filters:
    console_url: "https://XXXXX.sentinelone.net"
    token: "XXXXXXXXXXXXXXXXXXXXXXXXXXX"
    site_name: "test"
    name: "MyFilter"
    filter_fields:
      computerName__contains: "MyComputerName"
      osTypes:
        - windows
```

Using computerName_contains as a String and not an array will break the deepdiff and therefore the status of the ansible module will always be change, what is not in the idempotent spirit of ansible.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
sentinelone_filters.py

##### ANSIBLE VERSION

```paste below
effects all versions
```
